
tab_spaces = 2
struct_variant_width = 70
array_width = 120
struct_lit_width = 120
chain_width = 120
max_width = 120
fn_call_width = 120
attr_fn_like_width = 120
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
